myWebsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path 
from django.urls import include 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('pollApp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pollApp/urls.py
from django.urls import path
from . import views

app_name='poll_app'
urlpatterns=[
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/results',views.results,name='results'),
    path('<int:question_id>/vote',views.vote,name='vote'),
    path('Add_Questions/',views.insert,name='insert'),
]

pollApp/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_asked
    question_asked = models.CharField(max_length=250)
    date_pub = models.DateTimeField(auto_now_add=True)
    def was_published_recently(self):
        return self.date_pub >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    def __str__(self):
        return self.choice_made
    question = models.ForeignKey(Question, on_delete=models.CASCADE) 
    choice_made = models.CharField(max_length=150)
    vote = models.IntegerField(default=0)

pollApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse
from django.db.models import F
from .models import Choice, Question
from django.template import loader


def index(request):
    latest_question_list = Question.objects.order_by('-date_pub')
    context = {
        'latest_question_list':latest_question_list,
    }
    return render(request, 'pollApp/index.html', context)

def detail(request, question_id):
    question= get_object_or_404(Question,pk=question_id)
    return render(request,'pollApp/detail.html',{'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'pollApp/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'pollApp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.vote = F('vote')+1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll_app:results', args=(question.id,)))

def insert(request):
    if request.method=='POST':
       _question = request.POST['_question']
       choice_one = request.POST["choice_one"]
       choice_two = request.POST["choice_two"]
       choice_three = request.POST["choice_three"]
       choice_four = request.POST["choice_four"]
       choice_five = request.POST["choice_five"]
       question_added=Question.objects.create(question_asked=_question)
       Choice.objects.create(choice_made=choice_one, question=question_added)
       Choice.objects.create(choice_made=choice_two, question=question_added)
       if choice_three:
          Choice.objects.create(choice_made=choice_three, question=question_added)
       if choice_four:   
          Choice.objects.create(choice_made=choice_four, question=question_added)
       if choice_five:
          Choice.objects.create(choice_made=choice_five, question=question_added)
       return redirect( 'poll_app:index')
    return render(request, 'pollApp/insert.html')        

pollApp/templates/pollApp/detail.html
<html>
    <body>
        <h1>{{ question.question_asked }}</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'poll_app:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_made }}</label><br>
            {% endfor %}
            <input type="submit" value="Vote">
        </form>
    </body>
</html>

pollApp/templates/pollApp/index.html
<html lang="en">
    <head>
          <title>Index</title>
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
          {% load static %}
          <link rel="stylesheet" type="text/css" href="{% static 'pollApp/style.css' %}">
    </head>

    <body>
    <div class='container'>
        {% if latest_question_list %}
        <ul>
           {% for question in latest_question_list %}
           <li><a href="{% url 'poll_app:detail' question.id %}">{{ question.question_asked }}</a></li>
           {% endfor %}
        </ul>
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
        <a href="{% url 'poll_app:insert' %}">If you want to add new question click here</a>
    </div>
    </body>
</html>

pollApp/templates/pollApp/insert.html
<html lang="en">
    <head>

    </head>
    <body>
        <form action="{% url 'poll_app:insert' %}" method="POST">
            {% csrf_token %}
           <p>Question:</p> <input type="text" name="_question" required>
           <br/>
           <p>Choice 1:</p> <input type="text" name="choice_one" required>
           <p>Choice 2:</p> <input type="text" name="choice_two" required>
           <p>Choice 3:</p> <input type="text" name="choice_three">
           <p>Choice 4:</p> <input type="text" name="choice_four">
           <p>Choice 5:</p> <input type="text" name="choice_five">
           <br/>
           <input type="submit"></input>
           <a href="{% url 'poll_app:index' %}">Go to home page</a>
        </form>
    </body>
</html>

pollApp/templates/pollApp/results.html
<html>
    <body>
        <h1>{{ question.question_text }}</h1>

        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_made }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
        {% endfor %}
        </ul>

        <a href="{% url 'poll_app:detail' question.id %}">Vote again?</a>
    </body>
</html>